


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Chloe Larsen, Rene Kruger & Kayla Beyers
 */
import javax.swing.*;
public class ChooseCarbonReport extends javax.swing.JFrame {

    /**
     * Creates new form ChooseCarbonReport
     */
    public ChooseCarbonReport() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlOptionChoice = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        btnCO2Emission = new javax.swing.JButton();
        btnGroupRide = new javax.swing.JButton();
        btnPackage = new javax.swing.JButton();
        btnReserve = new javax.swing.JButton();
        btnRide = new javax.swing.JButton();
        btnTravel = new javax.swing.JButton();
        lblOption = new javax.swing.JLabel();
        Separator = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Choose CO2 Emissions");

        pnlOptionChoice.setBackground(new java.awt.Color(255, 255, 255));

        btnBack.setFont(new java.awt.Font("Tahoma", 0, 20)); // NOI18N
        btnBack.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Back Button.png"))); // NOI18N
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnCO2Emission.setForeground(new java.awt.Color(255, 255, 255));
        btnCO2Emission.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/CO2 Emmisions Button.png"))); // NOI18N
        btnCO2Emission.setBorder(null);
        btnCO2Emission.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCO2EmissionActionPerformed(evt);
            }
        });

        btnGroupRide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Group Ride Button.png"))); // NOI18N
        btnGroupRide.setBorder(null);
        btnGroupRide.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnGroupRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGroupRideActionPerformed(evt);
            }
        });

        btnPackage.setForeground(new java.awt.Color(255, 255, 255));
        btnPackage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Packages Button.png"))); // NOI18N
        btnPackage.setBorder(null);
        btnPackage.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnPackage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPackageActionPerformed(evt);
            }
        });

        btnReserve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Reserve Button.png"))); // NOI18N
        btnReserve.setBorder(null);
        btnReserve.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnReserve.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReserveActionPerformed(evt);
            }
        });

        btnRide.setForeground(new java.awt.Color(255, 255, 255));
        btnRide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Ride Button.png"))); // NOI18N
        btnRide.setBorder(null);
        btnRide.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnRide.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRideActionPerformed(evt);
            }
        });

        btnTravel.setForeground(new java.awt.Color(255, 255, 255));
        btnTravel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Travel Button.png"))); // NOI18N
        btnTravel.setBorder(null);
        btnTravel.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnTravel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTravelActionPerformed(evt);
            }
        });

        lblOption.setFont(new java.awt.Font("Uber Move", 1, 48)); // NOI18N
        lblOption.setText("Chose an option");

        Separator.setForeground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout pnlOptionChoiceLayout = new javax.swing.GroupLayout(pnlOptionChoice);
        pnlOptionChoice.setLayout(pnlOptionChoiceLayout);
        pnlOptionChoiceLayout.setHorizontalGroup(
            pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionChoiceLayout.createSequentialGroup()
                .addGroup(pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 1261, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(pnlOptionChoiceLayout.createSequentialGroup()
                            .addGap(16, 16, 16)
                            .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(lblOption, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(pnlOptionChoiceLayout.createSequentialGroup()
                            .addGap(11, 11, 11)
                            .addComponent(btnRide, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnCO2Emission, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnGroupRide, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(btnTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlOptionChoiceLayout.setVerticalGroup(
            pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlOptionChoiceLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblOption, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Separator, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 24, Short.MAX_VALUE)
                .addGroup(pnlOptionChoiceLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(btnCO2Emission, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRide, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(btnPackage, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGroupRide, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReserve, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTravel, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(pnlOptionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(pnlOptionChoice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCO2EmissionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCO2EmissionActionPerformed
        CarbonEmissionReport jFCarbonEmissionReport = new CarbonEmissionReport();//Creating an object to access the next JFrame
        jFCarbonEmissionReport.show(); // Opening JFrame with CarbonEmissionReport
        dispose(); // closing ChooseCarbonReport JFrame
       jFCarbonEmissionReport.displayTotalCarbonFOrUser();//Method, found in the CarbonEmissionReport class, called to output the total carbon used by the user for the month into the next field in the next window
       jFCarbonEmissionReport.displayTblRide();//Method, found in the CarbonEmissionReport class, called to output the total database, sorted for the specific user, in the table in the next window
    }//GEN-LAST:event_btnCO2EmissionActionPerformed

    private void btnPackageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPackageActionPerformed
        JOptionPane.showMessageDialog(null, "Click the CO2 Emission Option");//informing the user to click the CO2 Emissions button
    }//GEN-LAST:event_btnPackageActionPerformed

    private void btnRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRideActionPerformed
        JOptionPane.showMessageDialog(null, "Click the CO2 Emission Option");//informing the user to click the CO2 Emissions button
    }//GEN-LAST:event_btnRideActionPerformed

    private void btnTravelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTravelActionPerformed
        JOptionPane.showMessageDialog(null, "Click the CO2 Emission Option");//informing the user to click the CO2 Emissions button
    }//GEN-LAST:event_btnTravelActionPerformed

    private void btnGroupRideActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGroupRideActionPerformed
        JOptionPane.showMessageDialog(null, "Click the CO2 Emission Option");//informing the user to click the CO2 Emissions button
    }//GEN-LAST:event_btnGroupRideActionPerformed

    private void btnReserveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReserveActionPerformed
        JOptionPane.showMessageDialog(null, "Click the CO2 Emission Option");//informing the user to click the CO2 Emissions button
    }//GEN-LAST:event_btnReserveActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        ChooseUser jFChooseUser = new ChooseUser();//Creating an object to access the first JFrame
        jFChooseUser.show(); // Opening JFrame with ChooseUser
        dispose(); // closing ChooseCarbonReport JFrame
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("FlatLaf Light".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChooseCarbonReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChooseCarbonReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChooseCarbonReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChooseCarbonReport.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ChooseCarbonReport().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator Separator;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCO2Emission;
    private javax.swing.JButton btnGroupRide;
    private javax.swing.JButton btnPackage;
    private javax.swing.JButton btnReserve;
    private javax.swing.JButton btnRide;
    private javax.swing.JButton btnTravel;
    private javax.swing.JLabel lblOption;
    private javax.swing.JPanel pnlOptionChoice;
    // End of variables declaration//GEN-END:variables
}
